Allow stdin as input for registry apply
apigee/registry pull request #985
Opened 2023-01-30 18:10 UTC by seaneganx

2023-01-30 20:27 UTC, timburks requested changes
Thanks for taking this on!

Mostly thinking aloud here: There's a directory structure described [on the wiki](https://github.com/apigee/registry/wiki/registry-apply#a-recommended-directory-structure-for-exported-registries). `registry export` writes registry contents into this structure and places spec contents in separate files alongside the `info.yaml` files that describe spec metadata. `registry apply` reads these directories and correctly picks up the spec files. That's illustrated in [this directory](https://github.com/apigee/registry/tree/main/cmd/registry/patch/testdata/sample-hierarchical)  and tested [here](https://github.com/apigee/registry/blob/8e09d5c4a35706ef7ea0080779b1efde29979abe/cmd/registry/patch/patch_project_test.go#L43). Since that passes, I think this is probably OK.

Tests here don't seem to be testing inline content (and I think that should be done in the patch package), but I'd like to hold that change anyway pending discussion in #989.

2023-01-30 20:27 UTC, timburks commented on cmd/registry/patch/apply.go
> +func addPatches(client connection.RegistryClient, patches *patchGroup, bytes []byte, fileName, parent string) error {
I think the role of this new function would be clearer if it was a method of patchGroup. Could you make that change and move this below the patchGroup struct declaration?

2023-01-30 20:32 UTC, timburks commented
@theganyo @seaneganx Is it surprising that there is no code coverage report for this PR? (it was to me, but maybe I'm missing something). I see in the action logs that an error was reported at the end of the compute code coverage step:
```
[2023-01-30T18:29:31.435Z] ['info'] Pinging Codecov: https://codecov.io/upload/v4?package=uploader-0.3.2&token=*******&branch=feat%2Fapply-stdin&build=4046939711&build_url=https%3A%2F%2Fgithub.com%2Fapigee%2Fregistry%2Factions%2Fruns%2F4046939711&commit=9beab1b73b73bd4774069756d6b3b19974c6abc5&job=Go&pr=985&service=github-actions&slug=apigee%2Fregistry&name=&tag=&flags=&parent=
[2023-01-30T18:29:31.815Z] ['error'] There was an error running the uploader: Error uploading to [https://codecov.io:](https://codecov.io/) Error: There was an error fetching the storage URL during POST: 404 - {'detail': ErrorDetail(string='Unable to locate build via Github Actions API. Please upload with the Codecov repository upload token to resolve issue.', code='not_found')}
```

2023-01-30 20:45 UTC, theganyo commented
> Is it surprising that there is no code coverage report for this PR?

Maybe https://community.codecov.com/t/upload-issues-unable-to-locate-build-via-github-actions-api/3954 ?

2023-02-02 18:15 UTC, timburks approved these changes
This looks great, thanks!

2023-02-02 20:32 UTC, merged